ALTER TABLE KHACHHANG
ALTER COLUMN DT varchar(8)

ALTER TABLE KHACHHANG
ALTER COLUMN TENKH nvarchar(30) NOT NULL

GO

ALTER TABLE VATTU
ALTER COLUMN TENVT nvarchar(30) NOT NULL

ALTER TABLE VATTU
ADD CONSTRAINT CHK_GiaMua CHECK (GIAMUA > 0) 

ALTER TABLE VATTU
ADD CONSTRAINT CHK_SLTon CHECK (SLTON >=0)

GO

ALTER TABLE HOADON
ADD CONSTRAINT FK_MAKH FOREIGN KEY (MAKH)  REFERENCES KHACHHANG(MAKH)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_MAHD FOREIGN KEY (MAHD) REFERENCES HOADON(MAHD)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT FK_MAVT FOREIGN KEY (MAVT) REFERENCES VATTU(MAVT)

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT DK_SL DEFAULT 1 FOR SL

ALTER TABLE CHITIETHOADON
ADD CONSTRAINT CHK_SL CHECK (SL > 0)	

SELECT * FROM VATTU