USE QLBanHang
SELECT * FROM KHACHHANG

SELECT * FROM KHACHHANG
WHERE DIACHI = 'TAN BINH'
ORDER BY MAKH

SELECT * FROM KHACHHANG
WHERE (DT IS NOT NULL AND EMAIL IS NOT NULL)

SELECT * FROM VATTU

SELECT * FROM VATTU
WHERE (GIAMUA >=20000 and GIAMUA <= 40000)
ORDER BY GIAMUA DESC

SELECT * FROM VATTU
WHERE TENVT LIKE '%GACH%'

SELECT count(*) as countVT
FROM VATTU

SELECT MAHD as MAHD, count(*) as countVT 
FROM CHITIETHOADON
GROUP BY MAHD

SELECT MAHD as MAHD,sum(GIABAN*SL) as GiaTriHD
FROM CHITIETHOADON
GROUP BY MAHD

SELECT MAKH, count(MAHD) as SLHD 
FROM HOADON
GROUP BY MAKH

SELECT * FROM HOADON
